### ISSUE TITLE
Possible enhancements from simonlogi fork

### ISSUE THREAD

**Issue by Troubladore** [toddwschneider/sec-13f-filings#10]
Hello, thank you so much for putting together this excellent repository!

I was browsing some of the recent forks, and found one that had a few of what the author thought were minor bug fixes. You can view them via this pull request: https://github.com/toddwschneider/sec-13f-filings/compare/main...simonlogi:sec-13f-filings:main

If they look to be of value, maybe they could be merged?

If not, feel free to close this issue.

Regards!

**Comment by toddwschneider** [comment]
@Troubladore thanks, but I don't see what bugs that code fixes. I'm inclined to close this issue, unless there's something specific you'd like to flag. Thanks

**Comment by Troubladore** [comment]
On reviewing it, it's probably more stylistic than anything. I'll go ahead and close this.
