### ISSUE TITLE
DAILY JOURNAL CORP 2Q2024 filing not picked it

### ISSUE THREAD

**Issue by Droidoes** [toddwschneider/sec-13f-filings#12]
It seems that Daily Journal Corp (https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000783412) 13F for 2Q2024, published on 2024-04-04, was not picked up by the app.  

The 13F list generated by this app is at https://13f.info/manager/0000783412-daily-journal-corp

**Comment by toddwschneider** [comment]
Hi @Droidoes, apologies if I'm missing something, but I see that filing listed on the page:

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/cbc31e47-3ff2-4b86-9088-968cf806e195">

First row in that table links here: https://13f.info/13f/000143774924011104-daily-journal-corp-q1-2024

I'm going to close this issue, but feel free to reopen if I'm misunderstanding something. Thanks!

**Comment by Droidoes** [comment]
Todd, you are correct.  I made a mistake. Thanks so much for answering my request!
