### ISSUE TITLE
CSV Version of Full SEC List

### ISSUE THREAD

**Issue by unspectacular** [toddwschneider/sec-13f-filings#3]
Hi @toddwschneider et al.  I found the csv version of the full quarterly 13F list to be extremely helpful and noticed it is no longer linked to.  Is this something still available for public use or has it not able to be linked to any more?  Keep up the great work.

**Comment by toddwschneider** [comment]
Hi @unspectacular, I'm not sure I understand exactly what you mean? What CSV and what list are you talking about? This repo fetches mostly XML and HTML from the SEC's website, then parses those into a Postgres database. Can you describe in more words what you're looking for? Thanks

**Comment by toddwschneider** [comment]
No worries! I'm going to "close" this issue then but feel free to reopen if something else comes up

**Comment by rl2050** [comment]
If someone is still looking to convert the quarterly list of 13f securities to CSV (or Excel).. I've created a python script for this purpose. See my repository here: [https://github.com/rl2050/13FtoExcel](https://github.com/rl2050/13FtoExcel)
@unspectacular
