### ISSUE TITLE
Any ideas about the meaning of these types?

### ISSUE THREAD

**Issue by CaledoniaProject** [toddwschneider/sec-13f-filings#8]
Do you have any ideas what these equity types means?

1. COM NEW
2. NOTE 1.125%10/1
3. *W EXP 11/05/202
4. RIGHT 04/04/2023

**Comment by toddwschneider** [comment]
Hi @CaledoniaProject, these are values that are passed through directly from SEC filings themselves. I suspect that "W" stands for Warrants, and "notes" probably refer to convertible notes, but again it's just whatever the filer puts in the form, and I have no specific knowledge about any filings

You can see a full list of 13f securities on the SEC's website here: https://www.sec.gov/files/investment/13flist2023q1.pdf

I'm going to close this issue as I don't think it's within scope of the GitHub repo, thanks
