### ISSUE TITLE
Question regarding how data is retrieved?

### ISSUE THREAD

**Issue by GuardianOfTheVoid** [toddwschneider/sec-13f-filings#9]
Thanka so much for this awesome repo (and the website).I am porting parts of the code to Python for a personal fun project. I was wondering if you could give me pointers on how you keep the 13f data up to date. Do you always get the master.idx using thirteen_f_filings and update from that or do you use latest_thirteen_f_filings to check for new filings on a regular basis, say everyday. Thanks for any tips!

**Comment by toddwschneider** [comment]
Hi @GuardianOfTheVoid , you can see this in the `clock.rb` file here: https://github.com/toddwschneider/sec-13f-filings/blob/main/clock.rb#L13-L26

It runs `latest_thirteen_f_filings` every 30 minutes, then also checks the master.idx file once per day as a backup in case the new filings job misses anything

I'm going to close this as an issue, but feel free to reopen if anything else, thanks
